[[redirects]]
  from = "/hotpic"
  to = "https://arhaanb.co/arhaan.png"

[[redirects]]
  from = "/hotpic2"
  to = "https://arhaanb.co/arhaanb2.jpg"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/vBmuT6E"

[[redirects]]
  from = "/terrano"
  to = "https://gh.arhaanb.co/terrano"
  
[[redirects]]
  from = "/GPL"
  to = "https://gpl.arhaanb.co"
  
[[redirects]]
  from = "/gpl"
  to = "https://gpl.arhaanb.co"
  
[[redirects]]
  from = "/byte"
  to = "https://minetbyte.netlify.app"

[[redirects]]
  from = "/elire"
  to = "https://elire.arhaanb.co"

[[redirects]]
  from = "/core"
  to = "https://elire.arhaanb.co"
  
[[redirects]]
  from = "/medica"
  to = "https://medica.arhaanb.co"
  
[[redirects]]
  from = "/medica/app"
  to = "https://medica-app.arhaanb.co"

[[redirects]]
  from = "/*"
  to = "index.html"
	status = 200
